@startuml
'https://plantuml.com/class-diagram

class ThueBao{
    int balance
    void napTien(int soTien)
    void thucHienCuocGoi(int soGiay)
    void print()
    void setState(IThueBaoState state)
}
class Normal
class Silver
class Gold
class IThueBaoState{
    void napTienHandle(int soTien, ThueBao thueBao)
    void thucHienCuocGoiHandle(int soGiay, ThueBao thueBao)
    void printHandle(ThueBao thueBao)
}

ThueBao --> IThueBaoState : state
IThueBaoState <|.. Normal
IThueBaoState <|.. Silver
IThueBaoState <|.. Gold

@enduml